### ISSUE TITLE
Migrate CoW Protocol V1 Abstractions to V2

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1590]
This will be a collection of incremental additions to the v2-engine models:

1. [x] Migrate [`gnosis_protocol_v2.view_solvers`](https://github.com/duneanalytics/spellbook/blob/main/deprecated-dune-v1-abstractions/ethereum/gnosis_protocol_v2/view_solvers.sql) - #1563
2. [x] Migrate [`gnosis_protocol_v2.trades`](https://github.com/duneanalytics/spellbook/blob/main/deprecated-dune-v1-abstractions/ethereum/gnosis_protocol_v2/insert_trades.sql) - #1580 
3. [x] Migrate [`gnosis_protocol_v2.batches`](https://github.com/duneanalytics/spellbook/blob/main/deprecated-dune-v1-abstractions/ethereum/gnosis_protocol_v2/insert_batches.sql) - #1587
4. [x] Create consolidation trades table which conforms to dex-trades columns - #1591
5. [ ] Create a dex_aggregators table - #1600
6. [ ] Insert into new `dex.trades` table
7. [ ] Add unit tests to trades and batches tables
8. [ ] (Optional) Build Solvers, Trades and Batches for Gnosis Chain

Note that the last three items can be tackled independently (i.e. in parallel).
