### ISSUE TITLE
EVM Balances main issue

### ISSUE THREAD

**Issue by aalan3** [duneanalytics/spellbook#4523]
This is the main issue for brining balances back alive.

EDIT: please see this [comment](https://github.com/duneanalytics/spellbook/issues/4523#issuecomment-1827582865) on the updated approach on this.

## Problem
We currently have several different implementations of transfers and a broken balances implementation. 

For example we have: 
* [Fungible transfers](https://github.com/duneanalytics/spellbook/blob/main/models/fungible/fungible_transfers.sql) which include both native and erc20 transfers
* [ERC20 transfers](https://github.com/duneanalytics/spellbook/tree/main/models/transfers) which calculates wallet balance changes. It also has different implementations including aggregations
* [Balances](https://github.com/duneanalytics/spellbook/tree/main/models/balances/ethereum) which builds on transfers but is currently broken (except for Polygon).
   * Balances in the current implementation is aggregated to day or hour

Additionally we have a bunch of PRs trying to fill in the gaps in different places.

## Goal
We want to have balances on Dune and have a one unified implementation that includes both erc20 tokens and native tokens (ETH, BNB etc). We currently have a bunch of different implementations or suggested implementations when it comes to either balances or transfers. The aim is to have one implementation.

The goals are:
* Implement a model for erc20 transfers and native transfers
* Implement balances that include wrapped tokens, native tokens and erc20 tokens
    * No longer aggregate on time, instead on blocks or transactions
* Clean up naming and use bring everything under proper namespaces

We consider NFT balances out of scope for this issue but it could be future work for both transfers (`nft_transfers` also already exists) and balances.

### Fungible transfers model
We can base our transfers table off `fungible` I think it does pretty much what we want when it comes to native and ERC20 transfers but the name and structure should change. 

We should have one table for both native and erc20 transfers

### Structure
Following the discussion in https://github.com/duneanalytics/spellbook/issues/4580#issuecomment-1767204966. We want the structure to be the following on new models and sector level spells
`base_model` (materialized) -> `enrichment_model` (view)

So for balances we would use the transfers base model to create the balances base model since balances will also be enriched in a view.

There might be cases where doing the enrichment in the view might not perform well, in those cases we can still materialize but we should try without it at first.

### Naming
This is a bit tricky. We currently have `transfers_erc20` and `fungible_transfers`, we should consider that new users might not know what `fungible` means or even `erc20`.  IMO we should use either `tokens`, `transfers` and/or `balances` namespaces for this. Naming suggestions are welcome
For example: 
     * `tokens_ethereum.transfers` or `tokens_ethereum.balances`. `tokens.transfers`/`tokens.balances` 
     * `ethereum.transfers`, `ethereum.balances` - or `transfers_ethereum.?` `balances_ethereum.block`? Not sure what the table name should be in this case

### Aggregations
The old design of balances which has kind of lingered along was done during the Postgres days and at the time we decided to aggregate balances on hours and days because we couldn't handle it performance-wise. Since moving to DuneSQL things have change. In my testing for example I could build balances without aggregation just fine. 

Aggregating on blocks could be a nicer user experience in some cases so we could potentially have both.

## Tasks 
This will be updated with sub issues.
- [ ] Fix transfers, convert fungible models to use a base model with a view on top https://github.com/duneanalytics/spellbook/issues/4521
- [ ] Balances model that includes both native and ERC20 https://github.com/duneanalytics/spellbook/pull/4640/
- [ ] Drop existing `fungible`, `transfers` and `balances`

**Comment by 0xRobin** [comment]
Sounds great!
My preferred naming would be:
`tokens.transfers`
- from
- to
- token_address
- amount

`tokens.balances`
- wallet_address
- token_address
- balance_change
- balance

For chain specific models I would follow the current convention of adding the suffix to the schema (resulting in `tokens_ethereum.transfers` and `tokens_ethereum.balances`)

**Comment by aalan3** [comment]
@hildobby thanks for the input here, really appreciate it! I'll try to address your comments below. 

 On `tokens.transfers` yeah we plan on getting nft transfers in there as well so that we can use it for balances. I just wanted to keep this issue focused on the non NFT ones that needs work as a start.

>For spellbook tables discoverability, I think that's a Dune-wide issue (much like dashboard/query discoverability, although those 2 are a bit better thanks to stars and more search options). Table discovery is horrendous rn unless you've built or know of the tables, I have no clue what new tables ppl have built lately, documentation for tables is nowhere on frontend (I used to use https://dune.com/spellbook#!/spellcasters but its been out of date for months) and it's a hassle to see who built what (I occasionally reach out to creator to get a better understanding of a spell). Imo no name change will fix discoverability, my guess is that being able to customise your table lists (something like Essentials could become My Essentials), or have recommended or "most used" lists, and better in-app documentation (+ maybe some light table usage stats) would help a lot more.

I agree that discoverability is a problem. We have a bunch of really great spells that most people will not discover because they are buried with thousands of other projects. We are working on improving this on our end. I've forwarded your feedback to the PM who owns this problem. We are also thinking about how to promote Spellbook tables more, suggestions are welcome.

Docs will be restored post migration, it became too heavy with all the duplicate models etc and started breaking.

>With Spellbook's lack of guidelines, I generally try to name tables so that names are the simplest possible and so you can easily tell what's in them just from the name. Is that the wrong approach?

Using the simplest name possible is the correct approach, I would just say that naming in general is a bit hard. In case of `fungible` for example, I don't think it's a bad name. It correctly describes the model, imho it's just a bit technical.

Regarding guidelines it's is something that we haven't done a good job on and need to improve. We want to share more learnings about performance and spell design with everyone. We will start cleaning up the readme and providing some better guidelines soon.

>I'm always happy to factor in feedback I get in PR discussions but if I need to start a github issue for every new table I create, I'll probably just stop creating on spellbook since spellbook PRs already aren't the easiest to put together. Increasing contribution complexity would just lead to fewer contributions rather than the opposite.
 
If you think that something is clear enough in a PR that's fine no need for an issue. In this case we created an issue because there are 20+ PRs open related to transfers and balances (which is mainly due to us not being clear about how to solve it), so we wanted to just organize this a bit better.


Want to explain our reasoning about issues a bit as well: The main reason we want to use issues is to be able to plan for things, organize better and have a discussion around potential problems and design when it comes to bigger sector level spells, like this one. It's also gives other people who cares about the issue to chime in.

The aim is not to have a process for the sake of process. The issues are meant for bigger things such as balances or for example big refactors or collaborating on Spells. The additional context can also help with reviewing PRs faster.

As the complexity of this project grows we simply need a way of organizing things and issues are generally a great way of doing that for other open source projects, so we wanted to try it here as well.

Another example of example of what we want to solve: we eventually want to have some sort of linting tool and format the code. We will communicate this via an issue to get input from the community. We have a number of tech debt problems that we can map out and solve this way.

>On balance tables, I never use those as I know they've always been inaccurate, for them to be fully reworked I would suggest having good transfer tables first that balance tables can be based on.

Yeah this is the goal, to create transfers first that we can then build a solid balances spell on top of.

**Comment by MSilb7** [comment]
For Balances on OP Mainnet (`optimism` in Dune)

There was a chain regenesis in Nov 2021, meaning all txs and transfers before then will not appear in the `optimism` schema.

There is a state dump here, where we can call `balanceof` for each user address x token combination. This should be the 'starting state' of balances for `optimism`. I can help with this if useful (i.e. list of active addresses and tokens + ETH): https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json

**Comment by aalan3** [comment]
Closing in favour of https://github.com/duneanalytics/spellbook/issues/5123
