### ISSUE TITLE
EVM balances second iteration

### ISSUE THREAD

**Issue by aalan3** [duneanalytics/spellbook#5123]
In https://github.com/duneanalytics/spellbook/issues/4523 we set out to build balances based off transfers. But realized that it's not feasible performance-wise. 

So instead we decided that we are going to just get all the data we need from the node(s) to create some raw tables which are then exposed via Spellbook. 

We will get balances for native tokens, ERC20, ERC721 and ERC1155, using nft.transfers, token.transfers, `transaction.to/from` and in the case of Ethereum `withdrawals`. For native tokens we will use `eth_getBalance` and ERC20 and ERC1155 it's `balanceOf`. For ERC721 we will use the token id and `ownerOf` instead of `balanceOf`, because `balanceOf` doesn't say which token(s) belongs to the address just how many. 

In this issue we will need to decide the what metadata should be added to the balances table, for example: 
* ERC20 and native symbol, decimals
* Prices for ERC20 and native tokens
* Metadata for NFTs, for example collection names

An example of a view without NFT metadata (for now, can be materialized later) can be found here https://github.com/duneanalytics/spellbook/pull/5101 for ethereum.

The raw Ethereum table is currently available here (not that it still updated manually once a day but will change soon): https://dune.com/queries/3296060

## Todos
- [ ] Decide on native/ERC20 metadata
- [ ] Decide on NFT metadata
- [ ] Document data quality
- [ ] Add support more chains (multiple are being backfilled atm)
