### ISSUE TITLE
Scroll Spellbook integration tracker

### ISSUE THREAD

**Issue by 0xRobin** [duneanalytics/spellbook#5436]
Small overview to track the integration of a new chain into spellbook
- [ ] base_sources
- [ ] tokens.[transfers | balances] 
- [ ] evm.*
- [ ] abi.signatures
- [ ] nft.[trades | transfers | approvals]
- [ ] dex.trades
- [ ] lending.[borrow | supply | flashloans]

**Comment by jeff-dude** [comment]
#5416 includes scroll
